name: Replace Strings

on:
  push:
    branches:
      - master # or any branches you want to trigger on push
  workflow_run:
    workflows: ["Upstream Sync"]
    types:
      - completed
    branches:
      - master # specify branches, if you want to limit when workflow_run is triggered


jobs:
  replace-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Replace Strings in Files
        run: |
          find . -type f -not -path '*/\.*' -exec sed -i 's/ghcr.io/ghcr.nju.edu.cn/g' {} +
          find . -type f -not -path '*/\.*' -exec sed -i 's/GitHub.com/hub.nuaa.cf/g' {} +

      - name: Commit changes
        run: |
          git config --global user.name 'Zhehan-Z (Bot)'
          git config --global user.email 'github@zhehanz.com'
          git commit -am "Replace URLs in files" || echo "No changes to commit"
          git push
